image: docker:latest
services:
  - docker:dind

variables:
  REGISTRY: "registry.bio.di.uminho.pt"
  IMAGE_PRODUCTION:  "${REGISTRY}/laura_duro/onmtreaction"
  DOCKER_FOLDER_PROD: "/builds/laura_duro/onmtreaction"

before_script:
  - export SHORT_SHA=$(echo $CI_COMMIT_SHA | cut -c 1-8)
  - export DATE=$(date +"%y%m%d.%H%M")
  - export TAG=${DATE}.${SHORT_SHA}

stages:
 - build-app

prod-build-app:
   stage: build-app
   tags:
      - docker-build
   script:
      - pwd
      - ls ${DOCKER_FOLDER_PROD} || true
      - if [ -z "${CI_COMMIT_TAG}" ]; then CI_COMMIT_TAG="latest"; fi;
      - echo "$CI_COMMIT_TAG" || true
      - docker build --build-arg app_version=${CI_COMMIT_TAG} -f ${DOCKER_FOLDER_PROD}/Docker/Dockerfile_onmtreaction -t ${IMAGE_PRODUCTION} ${DOCKER_FOLDER_PROD}
      - docker tag ${IMAGE_PRODUCTION} ${IMAGE_PRODUCTION}:${CI_COMMIT_TAG}
      - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $REGISTRY
      - docker push ${IMAGE_PRODUCTION}
      - docker push ${IMAGE_PRODUCTION}:${CI_COMMIT_TAG}
   only:
      - master
      - tags




