FROM nvidia/cuda:11.1.1-cudnn8-runtime-ubuntu18.04

# Install system packages
WORKDIR /root

ENV PYTHONDONTWRITEBYTECODE=1
ENV LANG=C.UTF-8

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-distutils \
        wget \
        nano \
        python-rdkit \
        librdkit1 \
        rdkit-data \
        && \
    wget -nv https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py && \
    apt-get autoremove -y wget && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip -q --no-cache-dir install --upgrade --upgrade-strategy only-if-needed pandas
RUN python3 -m pip -q --no-cache-dir install --upgrade --upgrade-strategy only-if-needed matplotlib
RUN python3 -m pip -q --no-cache-dir install --upgrade --upgrade-strategy only-if-needed seaborn

COPY OpenNMT-py/ /home/OpenNMT-py
WORKDIR /home/OpenNMT-py
RUN python3 -m pip -q --no-cache-dir install -e .
#RUN python3 -m pip -q --no-cache-dir install -r requirements.opt.txt

ENV LANG=C.UTF-8

WORKDIR /home