FROM nvidia/cuda:11.1.1-cudnn8-runtime-ubuntu18.04

# Install system packages
WORKDIR /root

ENV PYTHONDONTWRITEBYTECODE=1
ENV LANG=C.UTF-8

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-distutils \
        wget \
        nano \
        python-rdkit \
        librdkit1 \
        rdkit-data \
        git \
        && \
    wget -nv https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py && \
    apt-get autoremove -y wget && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip -q --no-cache-dir install --upgrade pandas
RUN python3 -m pip -q --no-cache-dir install --upgrade matplotlib
RUN python3 -m pip -q --no-cache-dir install --upgrade seaborn
RUN python3 -m pip -q --no-cache-dir install git+https://github.com/OpenNMT/OpenNMT-py.git
#RUN python3 -m pip -q --no-cache-dir install --upgrade --upgrade-strategy only-if-needed git+https://github.com/OpenNMT/OpenNMT-py.git

ENV LANG=C.UTF-8

WORKDIR /home