FROM nvidia/cuda:11.1.1-cudnn8-runtime-ubuntu18.04

# Install system packages
WORKDIR /root

ENV PYTHONDONTWRITEBYTECODE=1
ENV LANG=C.UTF-8

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
	nano \
    && \
    rm -rf /var/lib/apt/lists/*

# Install conda
ENV CONDA_DIR /opt/conda
ENV PATH $CONDA_DIR/bin:$PATH

RUN MINICONDA="Miniconda3-latest-Linux-x86_64.sh" && \
    wget --quiet https://repo.continuum.io/miniconda/$MINICONDA && \
    bash $MINICONDA -b -p /miniconda && \
    rm -f $MINICONDA

ENV PATH /miniconda/bin:$PATH

#Install python and packages
ARG python_version=3.9

RUN conda update -n base -c defaults conda -y
RUN conda install -y -c anaconda pandas && conda clean -afy
RUN conda install -y -c anaconda matplotlib && conda clean -afy
RUN conda install -y -c anaconda seaborn && conda clean -afy
RUN conda install -y -c anaconda notebook && conda clean -afy
RUN conda install -y -c anaconda python=${python_version}

RUN conda install -y -c rdkit rdkit && conda clean -afy
RUN python3 -m pip -q --no-cache-dir install --upgrade pip
RUN python3 -m pip -q --no-cache-dir install --upgrade --upgrade-strategy only-if-needed python3-distutils
RUN python3 -m pip -q --no-cache-dir install --upgrade --upgrade-strategy only-if-needed git+https://github.com/OpenNMT/OpenNMT-py.git

ENV LANG=C.UTF-8

WORKDIR /home
