# this is our first build stage, it will not persist in the final image
FROM ubuntu as intermediate

# install git
RUN apt-get update
RUN apt-get install -y git

# add credentials on build
ARG SSH_KEY=""
RUN mkdir /root/.ssh/
RUN echo "${SSH_KEY}" > /root/.ssh/id_rsa
RUN cat /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa

# make sure your domain is accepted
RUN touch /root/.ssh/known_hosts
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts

RUN git clone git@github.com:BioSystemsUM/onmtreaction.git



#RUN apt-get update -qq && \
#  apt-get install -y --no-install-recommends \
#  git ssh
